sudo: false

language: scala

matrix:
  include:
    - jdk: oraclejdk11
    - jdk: openjdk8
    - jdk: openjdk11

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt scalafmtCheck +test docs/mdoc
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers


scala:
  - 2.12.10

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
