name: Scala CI

on: [push]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java: ['1.8.0', '11.0.x', '13.0.x']
        scala: ['2.12.10']
    steps:
    - name: printstuff
      run: echo branch ${{github.ref}}
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-scala-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-scala-${{ matrix.scala }}-
    - name: Run `static analysis`
      run: sbt checkAll
    - name: Run `compile`
      run: sbt +compile
    - name: Run `test`
      run: sbt +test
  publish:
    timeout-minutes: 10
    if: github.ref == 'master'
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Publish
        run: echo "publish"
